import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  // 헤더 스타일
  headerContainer: {
    backgroundColor: '#FFFFFF',
    paddingTop: 12,
    paddingBottom: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#868E96',
    fontWeight: '400',
  },
  writeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF8C42',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    gap: 4,
  },
  writeButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // 탭 스타일
  tabContainer: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  tabScrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 8,
  },
  tabButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#F8F9FA',
  },
  tabButtonActive: {
    backgroundColor: '#000000',
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#495057',
  },
  tabButtonTextActive: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 20,
  },
  // 포스트 카드 스타일
  postCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  postItem: {
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  postItemContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  postChevron: {
    marginLeft: 'auto',
  },
  postProfileImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E9ECEF',
  },
  postItemRight: {
    flex: 1,
    marginRight: 4,
  },
  postMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    gap: 6,
  },
  postCategoryTag: {
    backgroundColor: '#E7F5FF',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  postCategoryTagText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#1971C2',
  },
  postMetaText: {
    fontSize: 12,
    color: '#868E96',
    fontWeight: '400',
  },
  postMenuButton: {
    marginLeft: 'auto',
    padding: 4,
  },
  postItemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 4,
    lineHeight: 22,
  },
  postItemPreview: {
    fontSize: 14,
    color: '#495057',
    lineHeight: 20,
  },
  postMainContent: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  postTextContent: {
    flex: 1,
  },
  postContentImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
  },
  postStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  postStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  postStatsText: {
    fontSize: 13,
    color: '#868E96',
    fontWeight: '400',
  },
  postStatsTextActive: {
    color: '#FF8FA3',
  },
  postActionButtons: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    allignItems: 'center',
  },
  postEditButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
    borderWidth: 1,
    borderColor: '#E9ECEF',
    flex: 1,
  },
  postEditButtonText: {
    fontSize: 13,
    color: '#495057',
    fontWeight: '600',
  },
  postDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#FFF5F5',
    borderWidth: 1,
    borderColor: '#FFE3E3',
    flex: 1,
  },
  postDeleteButtonText: {
    fontSize: 13,
    color: '#FF6B6B',
    fontWeight: '600',
  },
  menuButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#F7FAFC',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 80,
  },
  emptyText: {
    fontSize: 16,
    color: '#718096',
    marginTop: 16,
    fontWeight: '600',
  },
  emptySubText: {
    fontSize: 14,
    color: '#CBD5E0',
    marginTop: 8,
    fontWeight: '500',
  },
  menuButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#F7FAFC',
  },
  // FAB 버튼 제거됨 (헤더에 글쓰기 버튼 있음)
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F7FA',
  },
  menuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  menuContainer: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    minWidth: 140,
    borderWidth: 1,
    borderColor: '#F7FAFC',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 12,
    borderRadius: 12,
  },
  menuItemText: {
    fontSize: 14,
    color: '#2D3748',
    fontWeight: '600',
  },
  menuItemDelete: {
    color: '#F56565',
  },
  searchContainer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  searchRow: {
    marginBottom: 14,
  },
  searchLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4A5568',
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  dateRangeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dateButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  dateButtonText: {
    fontSize: 14,
    color: '#4A5568',
    fontWeight: '500',
  },
  dateSeparator: {
    fontSize: 14,
    color: '#A0AEC0',
    fontWeight: '600',
  },
  searchInput: {
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#2D3748',
  },
  sortContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  sortButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  sortButtonActive: {
    backgroundColor: '#FFF5F7',
    borderColor: '#FF8FA3',
  },
  sortButtonText: {
    fontSize: 13,
    color: '#718096',
    fontWeight: '600',
  },
  sortButtonTextActive: {
    color: '#FF8FA3',
    fontWeight: '700',
  },
  searchButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  resetButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  resetButtonText: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '600',
  },
  searchSubmitButton: {
    flex: 2,
    flexDirection: 'row',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#FF8FA3',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  searchSubmitButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '700',
  },
});
