import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  categoryContainer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  categoryTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2D3748',
    marginBottom: 14,
    letterSpacing: -0.3,
  },
  radioGroup: {
    flexDirection: 'row',
    gap: 10,
    paddingRight: 20,
  },
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 24,
    backgroundColor: '#F7FAFC',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
  },
  radioButtonActive: {
    backgroundColor: '#FFF5F7',
    borderColor: '#FF8FA3',
    shadowColor: '#FF8FA3',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  radioCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#CBD5E0',
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioCircleActive: {
    borderColor: '#FF8FA3',
  },
  radioCircleInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FF8FA3',
  },
  radioLabel: {
    fontSize: 14,
    color: '#4A5568',
    fontWeight: '600',
  },
  radioLabelActive: {
    color: '#FF8FA3',
    fontWeight: '700',
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 90,
  },
  postContainer: {
    marginBottom: 16,
    width: '100%',
  },
  postLeft: {
    alignSelf: 'flex-start',
    width: width * 0.78,
  },
  postRight: {
    alignSelf: 'flex-end',
    width: width * 0.78,
  },
  postCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F7FAFC',
  },
  postCardMine: {
    backgroundColor: '#FFF5F7',
    borderColor: '#FFE4E9',
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  profileImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#F7FAFC',
  },
  postUserInfo: {
    flex: 1,
  },
  postUsername: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A202C',
    marginBottom: 3,
    letterSpacing: -0.2,
  },
  postTime: {
    fontSize: 12,
    color: '#A0AEC0',
    fontWeight: '500',
  },
  postContent: {
    fontSize: 15,
    lineHeight: 23,
    color: '#2D3748',
    marginBottom: 14,
    letterSpacing: -0.1,
  },
  postTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1A202C',
    marginBottom: 10,
    lineHeight: 24,
    letterSpacing: -0.3,
  },
  categoryBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF5F7',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#FFE4E9',
  },
  categoryBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FF8FA3',
    letterSpacing: -0.1,
  },
  postFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#F1F3F5',
    marginTop: 4,
  },
  postActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: '#F7FAFC',
  },
  actionText: {
    fontSize: 13,
    color: '#718096',
    fontWeight: '600',
  },
  actionTextActive: {
    color: '#FF8FA3',
  },
  menuButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#F7FAFC',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 80,
  },
  emptyText: {
    fontSize: 16,
    color: '#718096',
    marginTop: 16,
    fontWeight: '600',
  },
  emptySubText: {
    fontSize: 14,
    color: '#CBD5E0',
    marginTop: 8,
    fontWeight: '500',
  },
  fabButton: {
    position: 'absolute',
    bottom: 28,
    right: 28,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FF8FA3',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF8FA3',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F7FA',
  },
  menuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  menuContainer: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    minWidth: 140,
    borderWidth: 1,
    borderColor: '#F7FAFC',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 12,
    borderRadius: 12,
  },
  menuItemText: {
    fontSize: 14,
    color: '#2D3748',
    fontWeight: '600',
  },
  menuItemDelete: {
    color: '#F56565',
  },
  searchContainer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  searchRow: {
    marginBottom: 14,
  },
  searchLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4A5568',
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  dateRangeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dateButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  dateButtonText: {
    fontSize: 14,
    color: '#4A5568',
    fontWeight: '500',
  },
  dateSeparator: {
    fontSize: 14,
    color: '#A0AEC0',
    fontWeight: '600',
  },
  searchInput: {
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#2D3748',
  },
  sortContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  sortButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  sortButtonActive: {
    backgroundColor: '#FFF5F7',
    borderColor: '#FF8FA3',
  },
  sortButtonText: {
    fontSize: 13,
    color: '#718096',
    fontWeight: '600',
  },
  sortButtonTextActive: {
    color: '#FF8FA3',
    fontWeight: '700',
  },
  searchButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  resetButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  resetButtonText: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '600',
  },
  searchSubmitButton: {
    flex: 2,
    flexDirection: 'row',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#FF8FA3',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  searchSubmitButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '700',
  },
});
