import { StyleSheet } from 'react-native';
import { commonStyles, colors, shadows } from './common.styles';

const styles = StyleSheet.create({
  // 공통 스타일 사용
  container: commonStyles.container,
  scrollView: commonStyles.scrollView,

  // 화면 특화 스타일
  content: {
    padding: 20,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    overflow: 'visible',
    ...shadows.small,
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4A4A4A',
    marginBottom: 12,
  },
  sectionHint: {
    fontSize: 13,
    color: '#999',
    backgroundColor: '#FFF9E6',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    lineHeight: 18,
  },
  required: {
    color: '#FF6B6B',
  },
  imageSection: {
    marginBottom: 0,
    overflow: 'visible',
    paddingVertical: 8,
  },
  imageList: {
    flexDirection: 'row',
    gap: 12,
    overflow: 'visible',
  },
  imageWrapper: {
    position: 'relative',
    overflow: 'visible',
  },
  charCountContainer: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    alignItems: 'flex-end',
    fontSize: 8,
    color: '#FFF',
  },
  image: {
    width: 120,
    height: 120,
    borderRadius: 12,
    backgroundColor: '#FFF5F0',
  },
  removeImageButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    zIndex: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  addImageButton: {
    width: 120,
    height: 120,
    borderRadius: 12,
    backgroundColor: '#FFF5F0',
    borderWidth: 2,
    borderColor: '#FFE5E5',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addImageText: {
    fontSize: 13,
    color: '#FFB6C1',
    marginTop: 8,
    fontWeight: '600',
  },
  inputSection: {
    marginBottom: 0,
  },
  titleInput: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4A4A4A',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFE5E5',
    borderRadius: 12,
    padding: 16,
  },
  contentInput: {
    fontSize: 16,
    color: '#4A4A4A',
    minHeight: 200,
    backgroundColor: '#FFF9F9',
    borderWidth: 1,
    borderColor: '#FFE5E5',
    borderRadius: 12,
    padding: 16,
    lineHeight: 24,
  },
  categoryIcon: {
    fontSize: 12,
  },
  categoryText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4A4A4A',
  },
  categoryTextActive: {
    color: '#FFFFFF',
  },
  categoryScroll: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#FFE5E5',
    backgroundColor: '#FFFFFF',
    marginRight: 10,
    gap: 6,
  },
  categoryButtonActive: {
    backgroundColor: '#FF9AA2',
    borderColor: '#FF9AA2',
  },
  tagsSection: {
    marginTop: 20,
    marginBottom: 0,
  },
  tagsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9F9',
    borderWidth: 1,
    borderColor: '#FFE5E5',
    borderRadius: 12,
    padding: 14,
    gap: 10,
  },
  tagsInput: {
    flex: 1,
    fontSize: 14,
    color: '#4A4A4A',
  },
  suggestionsContainer: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFE5E5',
    borderRadius: 12,
    marginTop: 8,
    maxHeight: 150,
  },
  suggestionItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#FFE5E5',
  },
  suggestionText: {
    fontSize: 14,
    color: '#FF9AA2',
    fontWeight: '600',
  },
  tagsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFE5E5',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
  },
  tagText: {
    fontSize: 14,
    color: '#FF9AA2',
    fontWeight: '600',
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: 12,
  },
  toggleButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#FFE5E5',
    borderRadius: 12,
    paddingVertical: 16,
    gap: 8,
  },
  toggleButtonActive: {
    backgroundColor: '#FF9AA2',
    borderColor: '#FF9AA2',
  },
  toggleButtonText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#999',
  },
  toggleButtonTextActive: {
    color: '#FFFFFF',
  },
  descriptionText: {
    fontSize: 12,
    color: '#999',
    marginTop: 8,
    lineHeight: 18,
  },
  publicSection: {
    marginBottom: 24,
  },
  publicButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  publicButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#FFE5E5',
    borderRadius: 12,
    paddingVertical: 14,
    gap: 8,
  },
  publicButtonActive: {
    backgroundColor: '#FF9AA2',
    borderColor: '#FF9AA2',
  },
  publicButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FF9AA2',
  },
  publicButtonTextActive: {
    color: '#FFFFFF',
  },
  footer: {
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#FFE5E5',
    shadowColor: '#FFB6C1',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  submitButton: {
    backgroundColor: '#FF9AA2',
    height: 52,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  submitButtonDisabled: {
    backgroundColor: '#CCC',
  },
  submitButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  // Toggle switch styles
  switch: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 60,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFE5E5',
    padding: 4,
  },
  switchActive: {
    backgroundColor: '#FFE5E5',
  },
  switchInactive: {
    backgroundColor: '#E0E0E0',
  },
  switchThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FF9AA2',
    marginRight: 8,
    transition: 'background-color 0.2s',
  },
  switchThumbActive: {
    backgroundColor: '#FF6B6B',
  },
  switchLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4A4A4A',
  },
});

export default styles;