import { StyleSheet } from 'react-native';
import { commonStyles, colors, shadows } from './common.styles';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFBF7' },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40, gap: 14 },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    shadowColor: '#FFB6C1',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#FFE5E5',
    gap: 10,
  },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#4A4A4A' },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: '#666', marginTop: 2 },
  genderRow: { flexDirection: 'row', gap: 10 },
  genderBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    backgroundColor: '#FAFAFA',
  },
  genderBtnActiveM: { borderColor: '#74B9FF', backgroundColor: '#EEF5FF' },
  genderBtnActiveW: { borderColor: '#FF9AA2', backgroundColor: '#FFF0F3' },
  genderBtnText: { fontSize: 14, fontWeight: '600', color: '#999' },
  genderBtnTextActive: { color: '#4A4A4A' },
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  inputBox: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: '#FFE0E5',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: '#4A4A4A',
    backgroundColor: '#FFFAFA',
  },
  inputUnit: { fontSize: 14, color: '#888', minWidth: 24 },
  inputRow2Col: { flexDirection: 'row', gap: 12 },
  labelRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  requiredMark: { fontSize: 13, fontWeight: '600', color: '#FF4D60' },
  searchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 14,
    gap: 8,
    marginTop: 6,
  },
  recordBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
    borderRadius: 14,
    gap: 8,
    marginTop: 8,
  },
  searchBtnText: { fontSize: 15, fontWeight: '700', color: '#FFFFFF' },
  loadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FFE5E5',
    paddingVertical: 12,
  },
  loadingText: { fontSize: 13, color: '#777', fontWeight: '500' },
  noticeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    padding: 12,
  },
  noticeText: {
    flex: 1,
    fontSize: 13,
    color: '#6E6E6E',
    lineHeight: 18,
  },
});

export default styles;
