import { StyleSheet } from 'react-native';
import { commonStyles, colors } from './common.styles';

const styles = StyleSheet.create({
  // 공통 스타일 사용
  container: commonStyles.container,
  content: commonStyles.content,

  keyboardView: {
    flex: 1,
  },
  // 화면 특화 스타일
  scrollContent: {
    padding: 12,
    paddingBottom: 300,
  },
  dateSection: {
    marginBottom: 24,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  dateGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    gap: 10,
  },
  dateText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  section: {
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F3F3F3',
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF9AA2',
    marginBottom: 14,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    paddingBottom: 10,
    borderBottomWidth: 1.5,
    borderBottomColor: '#FFF0F3',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    paddingBottom: 10,
    borderBottomWidth: 1.5,
    borderBottomColor: '#FFF0F3',
  },
  sectionTitleCompact: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  requestIngredientButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFF5F7',
    borderRadius: 14,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#FFD9E0',
  },
  requestIngredientButtonText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FF6B7A',
  },
  categoryScroll: {
    marginHorizontal: -18,
    paddingHorizontal: 18,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#FFE5E5',
    backgroundColor: '#FFFFFF',
    marginRight: 10,
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  categoryButtonActive: {
    borderRadius: 24,
    marginRight: 10,
    overflow: 'hidden',
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 2,
  },
  categoryButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 18,
    gap: 6,
  },
  categoryIcon: {
    fontSize: 10,
  },
  categoryText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#4A4A4A',
  },
  categoryTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 18,
    fontSize: 12,
    color: '#2D2D2D',
    borderWidth: 2,
    borderColor: '#FFE5E5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  textArea: {
    minHeight: 140,
    maxHeight: 200,
    lineHeight: 24,
  },
  charCount: {
    fontSize: 10,
    color: '#999999',
    textAlign: 'right',
    marginTop: 6,
    fontWeight: '500',
  },
  tagInputContainer: {
    gap: 6,
  },
  tagInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  suggestionsContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#FFE5E5',
    overflow: 'hidden',
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  suggestionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#FFF5F6',
    borderBottomWidth: 1,
    borderBottomColor: '#FFE5E5',
  },
  suggestionsHeaderText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FF9AA2',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#FFF0F3',
    gap: 4,
  },
  suggestionItemLast: {
    borderBottomWidth: 0,
  },
  suggestionHash: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FF9AA2',
    marginRight: 2,
  },
  suggestionText: {
    flex: 1,
    fontSize: 12,
    color: '#2D2D2D',
    fontWeight: '600',
  },
  tagInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 18,
    fontSize: 13,
    color: '#2D2D2D',
    borderWidth: 2,
    borderColor: '#FFE5E5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  tagAddButton: {
    width: 52,
    height: 52,
    backgroundColor: '#FF9AA2',
    borderRadius: 14,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  tagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF0F3',
    paddingVertical: 8,
    paddingLeft: 14,
    paddingRight: 10,
    borderRadius: 20,
    gap: 6,
    borderWidth: 1.5,
    borderColor: '#FFD4DB',
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  tagText: {
    fontSize: 11,
    color: '#FF6B7A',
    fontWeight: '700',
  },
  tagRemoveButton: {
    padding: 2,
  },
  submitButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
    marginBottom: 24,
  },
  analyzeButton: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#84FAB0',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 7,
  },
  analyzeButtonInner: {
    padding: 20,
    alignItems: 'center',
  },
  analyzeButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  submitButton: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  submitButtonInner: {
    padding: 20,
    alignItems: 'center',
  },
  submitButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  // 이미지 관련 스타일
  imageButtonContainer: {
    flexDirection: 'row',
    gap: 14,
  },
  imageButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 12,
    borderWidth: 2,
    borderColor: '#FFE5E5',
    borderStyle: 'dashed',
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  imageButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FF9AA2',
  },
  imagePreviewContainer: {
    position: 'relative',
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  imagePreview: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imageRemoveButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  // 토글 버튼 그룹
  buttonGroup: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 8,
    marginBottom: 10,
  },
  toggleButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#FFE5E5',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  toggleButtonActive: {
    backgroundColor: '#FF9AA2',
    borderColor: '#FF9AA2',
    shadowColor: '#FF9AA2',
    shadowOpacity: 0.4,
    elevation: 5,
  },
  toggleButtonText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#4A4A4A',
  },
  toggleButtonTextActive: {
    color: '#FFFFFF',
  },
  descriptionText: {
    fontSize: 11,
    color: '#999',
    marginTop: 4,
  },

  // 재료 입력 영역
  ingredientCatChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#FFE0E5',
    backgroundColor: '#FAFAFA',
  },
  ingredientCatChipActive: {
    backgroundColor: '#FF9AA2',
    borderColor: '#FF9AA2',
  },
  ingredientCatIcon: {
    fontSize: 13,
  },
  ingredientCatLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#666',
  },
  ingredientCatLabelActive: {
    color: '#FFFFFF',
  },
  ingredientListBox: {
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#FFE5E5',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    marginBottom: 4,
  },
  ingredientSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#FFF8F9',
  },
  ingredientSearchInput: {
    flex: 1,
    fontSize: 12,
    color: '#2D2D2D',
    paddingVertical: 0,
  },
  ingredientListDivider: {
    height: 1,
    backgroundColor: '#FFE5E5',
  },
  ingredientScrollList: {
    maxHeight: 220,
  },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#FFF5F6',
  },
  ingredientRowSelected: {
    backgroundColor: '#FFF5F7',
  },
  ingredientCheckCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#DDD',
    backgroundColor: '#F8F8F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ingredientCheckCircleActive: {
    backgroundColor: '#FF9AA2',
    borderColor: '#FF9AA2',
  },
  ingredientRowText: {
    flex: 1,
    fontSize: 12,
    color: '#4A4A4A',
    fontWeight: '500',
  },
  ingredientRowTextSelected: {
    color: '#FF6B7A',
    fontWeight: '700',
  },
  allergyBadge: {
    backgroundColor: '#FFF0E0',
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: '#FFD4A0',
  },
  allergyBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#E07000',
  },
  ingredientEmptyRow: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  ingredientEmptyText: {
    fontSize: 12,
    color: '#C8C8C8',
  },
  amountModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  amountModalContainer: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingVertical: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
  },
  amountModalTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FF6B7A',
    marginBottom: 8,
  },
  amountModalDescription: {
    fontSize: 12,
    color: '#4A4A4A',
    fontWeight: '600',
    marginBottom: 16,
  },
  amountButtonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  amountButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#FFD3D9',
    paddingVertical: 12,
    backgroundColor: '#FFF6F8',
  },
  amountButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FF6B7A',
  },
  amountCircles: {
    fontSize: 10,
    color: '#FF6B7A',
    fontWeight: '700',
    marginBottom: 4,
    letterSpacing: 1,
  },
  amountModalCancelButton: {
    marginTop: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  amountModalCancelText: {
    fontSize: 12,
    color: '#999999',
    fontWeight: '600',
  },
  requestModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  requestModalContainer: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  requestModalTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FF6B7A',
    marginBottom: 6,
  },
  requestModalDescription: {
    fontSize: 12,
    color: '#666666',
    marginBottom: 12,
    fontWeight: '600',
  },
  requestModalInput: {
    borderWidth: 1.5,
    borderColor: '#FFE0E5',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 12,
    color: '#333333',
    backgroundColor: '#FFFDFD',
  },
  requestModalButtonRow: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  requestModalCancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#F3F3F3',
  },
  requestModalCancelText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#666666',
  },
  requestModalSubmitButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#FF9AA2',
  },
  requestModalSubmitText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});

export default styles;