import { StyleSheet } from 'react-native';
import { commonStyles, colors, shadows } from './common.styles';

const styles = StyleSheet.create({
  // 공통 스타일 사용
  content: commonStyles.content,

  // 화면 특화 스타일
  container: {
    flex: 1,
    backgroundColor: '#FFF9F5',
  },
  profileSection: {
    backgroundColor: colors.background,
    padding: 24,
    alignItems: 'center',
    marginBottom: 12,
    ...shadows.medium,
  },
  profileImage: {
    width: 110,
    height: 110,
    borderRadius: 55,
    marginBottom: 16,
    borderWidth: 3,
    borderColor: colors.border,
  },
  nickname: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 6,
  },
  email: {
    fontSize: 14,
    color: colors.text.light,
    marginBottom: 10,
  },
  description: {
    fontSize: 14,
    color: '#7A7A7A',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
    paddingHorizontal: 20,
  },
  statsContainer: {
    flexDirection: 'row',
    width: '100%',
    paddingVertical: 18,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#FFE5E5',
    marginBottom: 20,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statDivider: {
    width: 1,
    backgroundColor: '#FFE5E5',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FF9AA2',
    marginBottom: 6,
  },
  statLabel: {
    fontSize: 13,
    color: '#B0B0B0',
    fontWeight: '500',
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    width: '100%',
    gap: 10,
  },
  followButton: {
    flex: 1,
    height: 48,
    backgroundColor: '#FF9AA2',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    gap: 6,
  },
  followButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },
  messageButton: {
    flex: 1,
    height: 48,
    borderWidth: 2,
    borderColor: '#FFE5E5',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    gap: 6,
  },
  messageButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FF9AA2',
  },
  moreButton: {
    width: 48,
    height: 48,
    borderWidth: 2,
    borderColor: '#FFE5E5',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF9F5',
  },
  errorText: {
    fontSize: 16,
    color: '#B0B0B0',
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 24,
  },
  retryButton: {
    backgroundColor: '#FF9AA2',
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 24,
    shadowColor: '#FF9AA2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  myFeedsSection: {
    backgroundColor: '#FFFBF7',
    padding: 20,
    marginBottom: 12,
    shadowColor: '#FFB6C1',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#4A4A4A',
  },
});

export default styles;